add_newline = false
scan_timeout = 10
format = """\
    $username\
    $hostname\
    $kubernetes\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $aws\
    $env_var\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $character\
    $status\
    """

[character]
success_symbol = "[➜](bold white)"
error_symbol = "[✖](bold red)"

[aws]
symbol = ""

[directory]
truncation_length = 0
style = "bold white"
read_only_symbol=" :"
read_only_symbol_style = "bold red"

[git_branch]
symbol = " "

[git_commit]
format = "[$hash]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[kubernetes]
disabled = false
style = "bold fg:#63b2e7"

[line_break]
disabled = true

[status]
style = "bold red"
symbol = ""
format = "[$status]($style) "
disabled = false
