name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run shellcheck tests
      run: make test
